blueprint:
  name: Frangisole Intelligente BTicino
  description: >
    Automazione avanzata per la gestione intelligente dei frangisole BTicino,
    con calcolo solare avanzato, tilt-up/down, privacy dinamica, logica climatica,
    override manuale e sicurezza.
  domain: automation
  source_url: "https://github.com/oraziopata/frangisole_intelligente_bticino"

input:

  cover_entity:
    name: Frangisole da controllare
    description: Seleziona uno o più frangisole BTicino compatibili.
    selector:
      target:
        entity:
          domain: cover

  azimut:
    name: Azimut della finestra (gradi)
    description: 0° Nord • 90° Est • 180° Sud • 270° Ovest.
    default: 180
    selector:
      number:
        min: 0
        max: 359
        step: 1

  distance:
    name: Distanza frangisole → pavimento (m)
    default: 0.5
    selector:
      number:
        min: 0.1
        max: 3.0
        step: 0.1

  max_height:
    name: Altezza totale frangisole (m)
    default: 2.1
    selector:
      number:
        min: 0.5
        max: 4.0
        step: 0.1

  default_position:
    name: Posizione di default quando il sole non è in FOV (%)
    default: 60
    selector:
      number:
        min: 0
        max: 100
        step: 1

  min_position:
    name: Posizione minima fisica consentita (%)
    default: 1
    selector:
      number:
        min: 0
        max: 100
        step: 1

  fov:
    name: Campo visivo totale (°)
    description: Ampiezza complessiva del FOV.
    default: 90
    selector:
      number:
        min: 10
        max: 120
        step: 1

  fov_left:
    name: Campo visivo a sinistra (°)
    default: 45
    selector:
      number:
        min: 0
        max: 120
        step: 1

  fov_right:
    name: Campo visivo a destra (°)
    default: 45
    selector:
      number:
        min: 0
        max: 120
        step: 1

  min_elevation:
    name: Elevazione minima del sole (°)
    default: 0
    selector:
      number:
        min: 0
        max: 45
        step: 1

  max_elevation:
    name: Elevazione massima del sole (°)
    default: 45
    selector:
      number:
        min: 10
        max: 90
        step: 1

  change_threshold:
    name: Soglia di movimento minima (%)
    description: Evita micro-movimenti inutili del motore.
    default: 1
    selector:
      number:
        min: 1
        max: 20
        step: 1

  cooldown_minutes:
    name: Tempo minimo tra movimenti (minuti)
    default: 1
    selector:
      number:
        min: 0
        max: 30
        step: 1

  privacy_mode:
    name: Modalità privacy
    default: "below_threshold"
    selector:
      select:
        options:
          - "always"
          - "sun_in_fov"
          - "below_threshold"
          - "off"

  privacy_min_position:
    name: Posizione minima per la privacy (%)
    default: 1
    selector:
      number:
        min: 0
        max: 100
        step: 1

  privacy_threshold:
    name: Soglia privacy (%)
    default: 20
    selector:
      number:
        min: 0
        max: 100
        step: 1

  tilt_up_enabled:
    name: Abilita Tilt-Up
    default: true
    selector:
      boolean: {}

  tilt_up_position:
    name: Posizione dopo il Tilt-Up (%)
    default: 1
    selector:
      number:
        min: 0
        max: 10
        step: 1

  tilt_up_apply_when_below:
    name: Applica Tilt-Up se target sotto questa soglia (%)
    default: 20
    selector:
      number:
        min: 0
        max: 100
        step: 1

  tilt_up_reset_delay:
    name: Ritardo (secondi) prima del Tilt-Up
    default: 3
    selector:
      number:
        min: 0
        max: 15
        step: 1

  tilt_down_enabled:
    name: Abilita Tilt-Down
    default: false
    selector:
      boolean: {}

  tilt_down_offset:
    name: Offset Tilt-Down (%)
    default: 2
    selector:
      number:
        min: 0
        max: 20
        step: 1

  climate_enabled:
    name: Abilita logica climatica
    default: false
    selector:
      boolean: {}

  rain_sensor:
    name: Sensore pioggia
    default: null
    selector:
      entity:
        domain: binary_sensor

  rain_action:
    name: Azione in caso di pioggia
    default: "close"
    selector:
      select:
        options:
          - "close"
          - "open"
          - "ignore"

  wind_sensor:
    name: Sensore vento
    default: null
    selector:
      entity:
        domain: sensor

  wind_threshold:
    name: Soglia vento (km/h)
    default: 30
    selector:
      number:
        min: 5
        max: 200
        step: 1

  door_sensor:
    name: Sensore porta finestra
    default: null
    selector:
      entity:
        domain: binary_sensor

  door_behavior:
    name: Comportamento porta aperta
    default: "ignore"
    selector:
      select:
        options:
          - "ignore"
          - "open_full"
          - "close_full"

  temp_sensor_inside:
    name: Sensore temperatura interna
    default: null
    selector:
      entity:
        domain: sensor

  temp_hot_threshold:
    name: Soglia caldo interno (°C)
    default: 27
    selector:
      number:
        min: 10
        max: 40
        step: 0.5

  temp_cold_threshold:
    name: Soglia freddo interno (°C)
    default: 18
    selector:
      number:
        min: 5
        max: 30
        step: 0.5

  presence_sensor:
    name: Sensore di presenza
    default: null
    selector:
      entity:
        domain: binary_sensor

  presence_timeout:
    name: Timeout presenza (min)
    default: 30
    selector:
      number:
        min: 0
        max: 120
        step: 1

  manual_override_entity:
    name: Interruttore override manuale
    default: null
    selector:
      entity:
        domain: input_boolean

  override_time:
    name: Durata override (min)
    default: 15
    selector:
      number:
        min: 1
        max: 180
        step: 1

  debug:
    name: Debug log
    default: false
    selector:
      boolean: {}

variables:

  # ENTITÀ
  cover: !input cover_entity

  # PARAMETRI GEOMETRICI
  azimut: !input azimut
  distance: !input distance
  max_height: !input max_height
  default_position: !input default_position
  min_position: !input min_position

  # CAMPO VISIVO / SOLE
  fov: !input fov
  fov_left: !input fov_left
  fov_right: !input fov_right
  min_elevation: !input min_elevation
  max_elevation: !input max_elevation

  # SOGLIE E LIMITI
  change_threshold: !input change_threshold
  cooldown_minutes: !input cooldown_minutes

  # PRIVACY
  privacy_mode: !input privacy_mode
  privacy_min_position: !input privacy_min_position
  privacy_threshold: !input privacy_threshold

  # TILT-UP
  tilt_up_enabled: !input tilt_up_enabled
  tilt_up_position: !input tilt_up_position
  tilt_up_apply_when_below: !input tilt_up_apply_when_below
  tilt_up_reset_delay: !input tilt_up_reset_delay

  # TILT-DOWN
  tilt_down_enabled: !input tilt_down_enabled
  tilt_down_offset: !input tilt_down_offset

  # LOGICA CLIMATICA
  climate_enabled: !input climate_enabled
  rain_sensor: !input rain_sensor
  rain_action: !input rain_action
  wind_sensor: !input wind_sensor
  wind_threshold: !input wind_threshold
  door_sensor: !input door_sensor
  door_behavior: !input door_behavior

  # TEMPERATURA / PRESENZA
  temp_sensor_inside: !input temp_sensor_inside
  temp_hot_threshold: !input temp_hot_threshold
  temp_cold_threshold: !input temp_cold_threshold
  presence_sensor: !input presence_sensor
  presence_timeout: !input presence_timeout

  # OVERRIDE MANUALE
  manual_override: !input manual_override_entity
  override_time: !input override_time

  # DEBUG
  debug: !input debug

  ###########################################
  #   ATTRIBUTI SOLE
  ###########################################
  sun_azimuth: "{{ state_attr('sun.sun', 'azimuth') }}"
  sun_elevation: "{{ state_attr('sun.sun', 'elevation') }}"

  gamma_rad: >
    {% set a = (azimut - sun_azimuth + 180) % 360 - 180 %}
    {{ a * pi / 180 }}

  fov_left_rad: "{{ fov_left * pi / 180 }}"
  fov_right_rad: "{{ fov_right * pi / 180 }}"
  elev_min_rad: "{{ min_elevation * pi / 180 }}"
  elev_max_rad: "{{ max_elevation * pi / 180 }}"
  sun_elev_rad: "{{ sun_elevation * pi / 180 }}"

  ###########################################
  #   SOLE DENTRO IL FOV?
  ###########################################
  sun_in_fov: >
    {{ gamma_rad >= -fov_left_rad and gamma_rad <= fov_right_rad
       and sun_elev_rad >= elev_min_rad
       and sun_elev_rad <= elev_max_rad }}

  ###########################################
  #   CALCOLO OMBRA / POSIZIONE IDEALE
  ###########################################
  sun_height_m: >
    {% if (sun_elev_rad | float) <= 0 %}
      9999
    {% else %}
      {{ distance / tan(sun_elev_rad) }}
    {% endif %}

  position_calc_raw: >
    {% set perc = (sun_height_m / max_height) * 100 %}
    {% if perc < 0 %}
      0
    {% elif perc > 100 %}
      100
    {% else %}
      {{ perc }}
    {% endif %}

  ###########################################
  #   PRIVACY DINAMICA
  ###########################################
  position_after_privacy: >
    {% set p = position_calc_raw | float %}
    {% if privacy_mode == "always" %}
      {{ max(p, privacy_min_position) }}

    {% elif privacy_mode == "sun_in_fov" %}
      {% if sun_in_fov %}
        {{ max(p, privacy_min_position) }}
      {% else %}
        {{ p }}
      {% endif %}

    {% elif privacy_mode == "below_threshold" %}
      {% if p < privacy_threshold %}
        {{ max(p, privacy_min_position) }}
      {% else %}
        {{ p }}
      {% endif %}

    {% else %}
      {{ p }}
    {% endif %}

  ###########################################
  #   TILT-DOWN (oscuramento leggero)
  ###########################################
  position_after_tilt_down: >
    {% set p = position_after_privacy | float %}
    {% if tilt_down_enabled %}
      {{ max(0, p - tilt_down_offset) }}
    {% else %}
      {{ p }}
    {% endif %}

  ###########################################
  #   TARGET PRE LIMITE
  ###########################################
  position_target_pre: >
    {% if sun_in_fov %}
      {{ position_after_tilt_down }}
    {% else %}
      {{ default_position }}
    {% endif %}

  ###########################################
  #   TARGET FINALE (rispetto min_position)
  ###########################################
  position_target: >
    {% set p = position_target_pre | float %}
    {% if p < min_position %}
      {{ min_position }}
    {% else %}
      {{ p }}
    {% endif %}
